version: '3.7'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - REACT_APP_ARTEMOTED_API_URL=http://localhost:8000/api
    command: npm start
